---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.99.100
    jenkins-agent-01:
      ansible_host: 158.160.110.182
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: jenkins
    ansible_ssh_private_key_file: /Users/e.a.erokhin/.ssh/mykey
