pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Molecule Test') {
            steps {
                sh 'molecule test'
            }
        }
    }
}